### ISSUE TITLE
 jetty9.4.7 (with PushCacheFilter) + haproxy in docker-network not pushing anything.

### ISSUE THREAD

**Issue by BodoWissemann** [eclipse/jetty.project#2068]
Hello,

i'm trying to use jetty's serverpush-feature with haproxy. I've set up Jetty 9.4.7 with PushCacheFilter and haproxy in two docker-containers.

I think jetty tries to push something, but no PUSH_PROMISE-frames are delivered to the client (I've checked chrome's net-internals-tab).

I'm not sure if this is an issue with jetty (maybe with h2c), haproxy or docker...? So please forgive me if this question is wrong here!

Here's my haporxy-config (taken from jetty's documentation):

```
global
tune.ssl.default-dh-param 1024

defaults
timeout connect 10000ms
timeout client 60000ms
timeout server 60000ms

frontend fe_http
mode http
bind *:80
# Redirect to https
redirect scheme https code 301

frontend fe_https
mode tcp
bind *:443 ssl no-sslv3 crt /usr/local/etc/domain.pem ciphers TLSv1.2 alpn h2,http/1.1
default_backend be_http

backend be_http
mode tcp
server domain basexhttp:8984
```

and here's how jetty starts:

```
[main] INFO org.eclipse.jetty.util.log - Logging initialized @377ms to org.eclipse.jetty.util.log.Slf4jLog
BaseX 9.0 beta 5cc42ae [HTTP Server]
[main] INFO org.eclipse.jetty.server.Server - jetty-9.4.7.v20170914
[main] INFO org.eclipse.jetty.webapp.StandardDescriptorProcessor - NO JSP Support for /, did not find org.eclipse.jetty.jsp.JettyJspServlet
[main] INFO org.eclipse.jetty.server.session - DefaultSessionIdManager workerName=node0
[main] INFO org.eclipse.jetty.server.session - No SessionScavenger set, using defaults
[main] INFO org.eclipse.jetty.server.session - Scavenging every 600000ms
[main] INFO org.eclipse.jetty.server.handler.ContextHandler - Started o.e.j.w.WebAppContext@7dc222ae{/,file:///opt/basex/webapp/,AVAILABLE}{/opt/basex/webapp}
[main] INFO org.eclipse.jetty.server.AbstractConnector - Started ServerConnector@3439f68d{h2c,[h2c, http/1.1]}{0.0.0.0:8984}
[main] INFO org.eclipse.jetty.server.Server - Started @784ms
HTTP Server was started (port: 8984).
HTTP Stop Server was started (port: 8985).
```

And here's the simple docker-compose.yml

```
version: '3.3'
services:

  basexhttp:
    container_name: pushcachefilter-basexhttp
    build: pushcachefilter-basexhttp/
    image: "pushcachefilter/basexhttp"
    volumes:
      - "${HOME}/data:/opt/basex/data"
      - "${HOME}/base/app-web/webapp:/opt/basex/webapp"
    networks:
      - web

  haproxy:
    container_name: haproxy_container
    build: ha-proxy/
    image: "my_haproxy"
    depends_on:
      - basexhttp
    ports: 
      - 80:80
      - 443:443
    networks:
      - web

networks:
  web:
    driver: overlay
```

Please note that i have to configure jetty using my own jetty.xml - the way shown in the documentation is not working for me.

Thx in advance

Bodo
